### PR TITLE
Export some members

### PR DESCRIPTION
**Pull request by cooligus**

### CODE REVIEW

**Comment by Capure** [comment]
As I'm not a high school student anymore, there is no way for me to test this. Would you guys be interested in taking the ownership of this repository?

**Comment by cooligus** [comment]
Of course, we discussed this issue and decided that we would be glad to maintain your API. You can change ownership of this repo to this organisation: https://github.com/Nasz-Elektryk/

**Comment by cooligus** [comment]
Comment for notification

**Comment by Capure** [comment]
I missed the notifications, sorry for the inconvenience. I've replied to Bartek's email with details regarding further steps.
Unfortunately, GitHub doesn't allow me to transfer this repo to your organization, because you already have a repository with the same name (the one this pull request is from), I've transferred the repository to Bartek, so that he can handle the rest of the process.

**Pull request merged**
